:doctype: book
:toc: left
:toclevels: 2
:source-highlighter: pygments
:source-language: C++
:prewrap!:
:pygments-style: vs
:icons: font
:stem: latexmath

= Vista

Bjørn Reese

== Introduction

Vista is a header-only C++11 library that contains various span classes.

The span classes acts like fixed-capacity in-place containers operating on contiguous memory provided by the user.

The span classes do not take ownership of the user-provided memory. User must ensure the life-time of the memory until the span has been destroyed.

[NOTE]
.Precondition
====
[source,c++]
----
using namespace vista;
----
====

== Span

Spans operate on borrowed continguous memory. Some <<rationale.adoc#,design decisions>> are common to all spans.

- <<circular/span.adoc#,Circular span>> is a circular queue operating on borrowed storage.
- <<map/span.adoc#,Map span>> is an associative array operating on borrowed storage.
- <<priority/span.adoc#,Priority span>> is a priority queue operating on borrowed storage.

== Fixed-Capacity Container

- <<circular/array.adoc#,Circular array>> is a circular queue operating on a nested array.

== Algorithm

- <<sorted/algorithm.adoc#,Sorted algorithms>> operate on sorted sequences.
